spring:
  flyway:
    locations: classpath:/db/testdata
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testweatherapidb;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect